# Minimal AzuGate Configuration
# This configuration provides basic reverse proxy functionality

server:
  port: 8080
  host: "0.0.0.0"

routes:
  # Default proxy - will be overridden by command line options
  - path: "/api/*"
    upstream:
      servers:
        - host: "localhost"
          port: 3000

# Optional: Enable metrics
metrics:
  enabled: true
  port: 9090

# Optional: Enable basic logging
logging:
  level: "info"
