port: 8080
admin_port: 50051
crt: "../resources/localhost.crt"
key: "../resources/localhost.key"
proxy_mode: false
authentication: false
auth_domain: "dev-uep626a5ecgmzopx.us.auth0.com"
auth_client_id: "wKWP9oGUySyMYDuISRTZ5EeGeB8SOl6F"
auth_client_secret: ""
