// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: config_service.proto
// Protobuf C++ Version: 5.28.3

#include "config_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace api {
namespace v1 {
              template <typename>
PROTOBUF_CONSTEXPR UpdateIpBlackListResponse::UpdateIpBlackListResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct UpdateIpBlackListResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateIpBlackListResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateIpBlackListResponseDefaultTypeInternal() {}
  union {
    UpdateIpBlackListResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateIpBlackListResponseDefaultTypeInternal _UpdateIpBlackListResponse_default_instance_;

inline constexpr UpdateIpBlackListRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ip_list_{},
        action_{static_cast< ::api::v1::UpdateIpBlackListRequest_ActionType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateIpBlackListRequest::UpdateIpBlackListRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateIpBlackListRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateIpBlackListRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateIpBlackListRequestDefaultTypeInternal() {}
  union {
    UpdateIpBlackListRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateIpBlackListRequestDefaultTypeInternal _UpdateIpBlackListRequest_default_instance_;

inline constexpr UpdateConfigResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : http_compression_{false},
        https_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateConfigResponse::UpdateConfigResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateConfigResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateConfigResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateConfigResponseDefaultTypeInternal() {}
  union {
    UpdateConfigResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateConfigResponseDefaultTypeInternal _UpdateConfigResponse_default_instance_;

inline constexpr UpdateConfigRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : path_{},
        http_compression_{false},
        https_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateConfigRequest::UpdateConfigRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateConfigRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateConfigRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateConfigRequestDefaultTypeInternal() {}
  union {
    UpdateConfigRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateConfigRequestDefaultTypeInternal _UpdateConfigRequest_default_instance_;

inline constexpr GetIpBlackListResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ip_list_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetIpBlackListResponse::GetIpBlackListResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetIpBlackListResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetIpBlackListResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetIpBlackListResponseDefaultTypeInternal() {}
  union {
    GetIpBlackListResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetIpBlackListResponseDefaultTypeInternal _GetIpBlackListResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR GetIpBlackListRequest::GetIpBlackListRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct GetIpBlackListRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetIpBlackListRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetIpBlackListRequestDefaultTypeInternal() {}
  union {
    GetIpBlackListRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetIpBlackListRequestDefaultTypeInternal _GetIpBlackListRequest_default_instance_;

inline constexpr GetConfigResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : http_compression_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetConfigResponse::GetConfigResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetConfigResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetConfigResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetConfigResponseDefaultTypeInternal() {}
  union {
    GetConfigResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetConfigResponseDefaultTypeInternal _GetConfigResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR GetConfigRequest::GetConfigRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct GetConfigRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetConfigRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetConfigRequestDefaultTypeInternal() {}
  union {
    GetConfigRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetConfigRequestDefaultTypeInternal _GetConfigRequest_default_instance_;
}  // namespace v1
}  // namespace api
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_config_5fservice_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_config_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_config_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::GetConfigRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::GetConfigResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::v1::GetConfigResponse, _impl_.http_compression_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateConfigRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateConfigRequest, _impl_.path_),
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateConfigRequest, _impl_.http_compression_),
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateConfigRequest, _impl_.https_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateConfigResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateConfigResponse, _impl_.http_compression_),
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateConfigResponse, _impl_.https_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::GetIpBlackListRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::GetIpBlackListResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::v1::GetIpBlackListResponse, _impl_.ip_list_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateIpBlackListRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateIpBlackListRequest, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateIpBlackListRequest, _impl_.ip_list_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::UpdateIpBlackListResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::api::v1::GetConfigRequest)},
        {8, -1, -1, sizeof(::api::v1::GetConfigResponse)},
        {17, -1, -1, sizeof(::api::v1::UpdateConfigRequest)},
        {28, -1, -1, sizeof(::api::v1::UpdateConfigResponse)},
        {38, -1, -1, sizeof(::api::v1::GetIpBlackListRequest)},
        {46, -1, -1, sizeof(::api::v1::GetIpBlackListResponse)},
        {55, -1, -1, sizeof(::api::v1::UpdateIpBlackListRequest)},
        {65, -1, -1, sizeof(::api::v1::UpdateIpBlackListResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::api::v1::_GetConfigRequest_default_instance_._instance,
    &::api::v1::_GetConfigResponse_default_instance_._instance,
    &::api::v1::_UpdateConfigRequest_default_instance_._instance,
    &::api::v1::_UpdateConfigResponse_default_instance_._instance,
    &::api::v1::_GetIpBlackListRequest_default_instance_._instance,
    &::api::v1::_GetIpBlackListResponse_default_instance_._instance,
    &::api::v1::_UpdateIpBlackListRequest_default_instance_._instance,
    &::api::v1::_UpdateIpBlackListResponse_default_instance_._instance,
};
const char descriptor_table_protodef_config_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024config_service.proto\022\006api.v1\032\034google/a"
    "pi/annotations.proto\"\022\n\020GetConfigRequest"
    "\">\n\021GetConfigResponse\022)\n\020http_compressio"
    "n\030\001 \001(\010R\017httpCompression\"j\n\023UpdateConfig"
    "Request\022\022\n\004path\030\001 \003(\tR\004path\022)\n\020http_comp"
    "ression\030\002 \001(\010R\017httpCompression\022\024\n\005https\030"
    "\003 \001(\010R\005https\"W\n\024UpdateConfigResponse\022)\n\020"
    "http_compression\030\001 \001(\010R\017httpCompression\022"
    "\024\n\005https\030\002 \001(\010R\005https\"\027\n\025GetIpBlackListR"
    "equest\"1\n\026GetIpBlackListResponse\022\027\n\007ip_l"
    "ist\030\001 \003(\tR\006ipList\"\320\001\n\030UpdateIpBlackListR"
    "equest\022C\n\006action\030\001 \001(\0162+.api.v1.UpdateIp"
    "BlackListRequest.ActionTypeR\006action\022\027\n\007i"
    "p_list\030\002 \003(\tR\006ipList\"V\n\nActionType\022\033\n\027AC"
    "TION_TYPE_UNSPECIFIED\020\000\022\023\n\017ACTION_TYPE_A"
    "DD\020\001\022\026\n\022ACTION_TYPE_REMOVE\020\002\"\033\n\031UpdateIp"
    "BlackListResponse2\255\003\n\rConfigService\022Q\n\tG"
    "etConfig\022\030.api.v1.GetConfigRequest\032\031.api"
    ".v1.GetConfigResponse\"\017\202\323\344\223\002\t\022\007/config\022d"
    "\n\014UpdateConfig\022\033.api.v1.UpdateConfigRequ"
    "est\032\034.api.v1.UpdateConfigResponse\"\031\202\323\344\223\002"
    "\023\"\016/config:update:\001*\022g\n\016GetIpBlackList\022\035"
    ".api.v1.GetIpBlackListRequest\032\036.api.v1.G"
    "etIpBlackListResponse\"\026\202\323\344\223\002\020\022\016/config/i"
    "plist\022z\n\021UpdateIpBlackList\022 .api.v1.Upda"
    "teIpBlackListRequest\032!.api.v1.UpdateIpBl"
    "ackListResponse\" \202\323\344\223\002\032\"\025/config/iplist:"
    "update:\001*B_\n\ncom.api.v1B\022ConfigServicePr"
    "otoP\001Z\004/api\242\002\003AXX\252\002\006Api.V1\312\002\006Api\\V1\342\002\022Ap"
    "i\\V1\\GPBMetadata\352\002\007Api::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_config_5fservice_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fapi_2fannotations_2eproto,
};
static ::absl::once_flag descriptor_table_config_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_config_5fservice_2eproto = {
    false,
    false,
    1194,
    descriptor_table_protodef_config_5fservice_2eproto,
    "config_service.proto",
    &descriptor_table_config_5fservice_2eproto_once,
    descriptor_table_config_5fservice_2eproto_deps,
    1,
    8,
    schemas,
    file_default_instances,
    TableStruct_config_5fservice_2eproto::offsets,
    file_level_enum_descriptors_config_5fservice_2eproto,
    file_level_service_descriptors_config_5fservice_2eproto,
};
namespace api {
namespace v1 {
const ::google::protobuf::EnumDescriptor* UpdateIpBlackListRequest_ActionType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_config_5fservice_2eproto);
  return file_level_enum_descriptors_config_5fservice_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t UpdateIpBlackListRequest_ActionType_internal_data_[] = {
    196608u, 0u, };
bool UpdateIpBlackListRequest_ActionType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr UpdateIpBlackListRequest_ActionType UpdateIpBlackListRequest::ACTION_TYPE_UNSPECIFIED;
constexpr UpdateIpBlackListRequest_ActionType UpdateIpBlackListRequest::ACTION_TYPE_ADD;
constexpr UpdateIpBlackListRequest_ActionType UpdateIpBlackListRequest::ACTION_TYPE_REMOVE;
constexpr UpdateIpBlackListRequest_ActionType UpdateIpBlackListRequest::ActionType_MIN;
constexpr UpdateIpBlackListRequest_ActionType UpdateIpBlackListRequest::ActionType_MAX;
constexpr int UpdateIpBlackListRequest::ActionType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class GetConfigRequest::_Internal {
 public:
};

GetConfigRequest::GetConfigRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:api.v1.GetConfigRequest)
}
GetConfigRequest::GetConfigRequest(
    ::google::protobuf::Arena* arena,
    const GetConfigRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetConfigRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:api.v1.GetConfigRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetConfigRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_GetConfigRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetConfigRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<GetConfigRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<GetConfigRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<GetConfigRequest>(), &GetConfigRequest::ByteSizeLong,
                &GetConfigRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetConfigRequest, _impl_._cached_size_),
            false,
        },
        &GetConfigRequest::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetConfigRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> GetConfigRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::GetConfigRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata GetConfigRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetConfigResponse::_Internal {
 public:
};

GetConfigResponse::GetConfigResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.v1.GetConfigResponse)
}
GetConfigResponse::GetConfigResponse(
    ::google::protobuf::Arena* arena, const GetConfigResponse& from)
    : GetConfigResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GetConfigResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetConfigResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.http_compression_ = {};
}
GetConfigResponse::~GetConfigResponse() {
  // @@protoc_insertion_point(destructor:api.v1.GetConfigResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetConfigResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetConfigResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetConfigResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetConfigResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetConfigResponse>(),
            ::google::protobuf::Message::GetNewImpl<GetConfigResponse>(),
            ::google::protobuf::Message::GetClearImpl<GetConfigResponse>(), &GetConfigResponse::ByteSizeLong,
                &GetConfigResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetConfigResponse, _impl_._cached_size_),
            false,
        },
        &GetConfigResponse::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetConfigResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetConfigResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::GetConfigResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool http_compression = 1 [json_name = "httpCompression"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(GetConfigResponse, _impl_.http_compression_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetConfigResponse, _impl_.http_compression_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool http_compression = 1 [json_name = "httpCompression"];
    {PROTOBUF_FIELD_OFFSET(GetConfigResponse, _impl_.http_compression_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetConfigResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:api.v1.GetConfigResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.http_compression_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetConfigResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetConfigResponse& this_ = static_cast<const GetConfigResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetConfigResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetConfigResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.v1.GetConfigResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool http_compression = 1 [json_name = "httpCompression"];
          if (this_._internal_http_compression() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_http_compression(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.v1.GetConfigResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetConfigResponse::ByteSizeLong(const MessageLite& base) {
          const GetConfigResponse& this_ = static_cast<const GetConfigResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetConfigResponse::ByteSizeLong() const {
          const GetConfigResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.v1.GetConfigResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool http_compression = 1 [json_name = "httpCompression"];
            if (this_._internal_http_compression() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetConfigResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetConfigResponse*>(&to_msg);
  auto& from = static_cast<const GetConfigResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.v1.GetConfigResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_http_compression() != 0) {
    _this->_impl_.http_compression_ = from._impl_.http_compression_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetConfigResponse::CopyFrom(const GetConfigResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.v1.GetConfigResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetConfigResponse::InternalSwap(GetConfigResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.http_compression_, other->_impl_.http_compression_);
}

::google::protobuf::Metadata GetConfigResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateConfigRequest::_Internal {
 public:
};

UpdateConfigRequest::UpdateConfigRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.v1.UpdateConfigRequest)
}
inline PROTOBUF_NDEBUG_INLINE UpdateConfigRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::api::v1::UpdateConfigRequest& from_msg)
      : path_{visibility, arena, from.path_},
        _cached_size_{0} {}

UpdateConfigRequest::UpdateConfigRequest(
    ::google::protobuf::Arena* arena,
    const UpdateConfigRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateConfigRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, http_compression_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, http_compression_),
           offsetof(Impl_, https_) -
               offsetof(Impl_, http_compression_) +
               sizeof(Impl_::https_));

  // @@protoc_insertion_point(copy_constructor:api.v1.UpdateConfigRequest)
}
inline PROTOBUF_NDEBUG_INLINE UpdateConfigRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : path_{visibility, arena},
        _cached_size_{0} {}

inline void UpdateConfigRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, http_compression_),
           0,
           offsetof(Impl_, https_) -
               offsetof(Impl_, http_compression_) +
               sizeof(Impl_::https_));
}
UpdateConfigRequest::~UpdateConfigRequest() {
  // @@protoc_insertion_point(destructor:api.v1.UpdateConfigRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UpdateConfigRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    UpdateConfigRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_UpdateConfigRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &UpdateConfigRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<UpdateConfigRequest>(),
            ::google::protobuf::Message::GetNewImpl<UpdateConfigRequest>(),
            ::google::protobuf::Message::GetClearImpl<UpdateConfigRequest>(), &UpdateConfigRequest::ByteSizeLong,
                &UpdateConfigRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(UpdateConfigRequest, _impl_._cached_size_),
            false,
        },
        &UpdateConfigRequest::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* UpdateConfigRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 39, 2> UpdateConfigRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::UpdateConfigRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated string path = 1 [json_name = "path"];
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateConfigRequest, _impl_.path_)}},
    // bool http_compression = 2 [json_name = "httpCompression"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UpdateConfigRequest, _impl_.http_compression_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateConfigRequest, _impl_.http_compression_)}},
    // bool https = 3 [json_name = "https"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UpdateConfigRequest, _impl_.https_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateConfigRequest, _impl_.https_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string path = 1 [json_name = "path"];
    {PROTOBUF_FIELD_OFFSET(UpdateConfigRequest, _impl_.path_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // bool http_compression = 2 [json_name = "httpCompression"];
    {PROTOBUF_FIELD_OFFSET(UpdateConfigRequest, _impl_.http_compression_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool https = 3 [json_name = "https"];
    {PROTOBUF_FIELD_OFFSET(UpdateConfigRequest, _impl_.https_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\32\4\0\0\0\0\0\0"
    "api.v1.UpdateConfigRequest"
    "path"
  }},
};

PROTOBUF_NOINLINE void UpdateConfigRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:api.v1.UpdateConfigRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.Clear();
  ::memset(&_impl_.http_compression_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.https_) -
      reinterpret_cast<char*>(&_impl_.http_compression_)) + sizeof(_impl_.https_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateConfigRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateConfigRequest& this_ = static_cast<const UpdateConfigRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateConfigRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateConfigRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.v1.UpdateConfigRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string path = 1 [json_name = "path"];
          for (int i = 0, n = this_._internal_path_size(); i < n; ++i) {
            const auto& s = this_._internal_path().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "api.v1.UpdateConfigRequest.path");
            target = stream->WriteString(1, s, target);
          }

          // bool http_compression = 2 [json_name = "httpCompression"];
          if (this_._internal_http_compression() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_http_compression(), target);
          }

          // bool https = 3 [json_name = "https"];
          if (this_._internal_https() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_https(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.v1.UpdateConfigRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateConfigRequest::ByteSizeLong(const MessageLite& base) {
          const UpdateConfigRequest& this_ = static_cast<const UpdateConfigRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateConfigRequest::ByteSizeLong() const {
          const UpdateConfigRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.v1.UpdateConfigRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string path = 1 [json_name = "path"];
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_path().size());
              for (int i = 0, n = this_._internal_path().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_path().Get(i));
              }
            }
          }
           {
            // bool http_compression = 2 [json_name = "httpCompression"];
            if (this_._internal_http_compression() != 0) {
              total_size += 2;
            }
            // bool https = 3 [json_name = "https"];
            if (this_._internal_https() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateConfigRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateConfigRequest*>(&to_msg);
  auto& from = static_cast<const UpdateConfigRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.v1.UpdateConfigRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_path()->MergeFrom(from._internal_path());
  if (from._internal_http_compression() != 0) {
    _this->_impl_.http_compression_ = from._impl_.http_compression_;
  }
  if (from._internal_https() != 0) {
    _this->_impl_.https_ = from._impl_.https_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateConfigRequest::CopyFrom(const UpdateConfigRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.v1.UpdateConfigRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateConfigRequest::InternalSwap(UpdateConfigRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.path_.InternalSwap(&other->_impl_.path_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateConfigRequest, _impl_.https_)
      + sizeof(UpdateConfigRequest::_impl_.https_)
      - PROTOBUF_FIELD_OFFSET(UpdateConfigRequest, _impl_.http_compression_)>(
          reinterpret_cast<char*>(&_impl_.http_compression_),
          reinterpret_cast<char*>(&other->_impl_.http_compression_));
}

::google::protobuf::Metadata UpdateConfigRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateConfigResponse::_Internal {
 public:
};

UpdateConfigResponse::UpdateConfigResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.v1.UpdateConfigResponse)
}
UpdateConfigResponse::UpdateConfigResponse(
    ::google::protobuf::Arena* arena, const UpdateConfigResponse& from)
    : UpdateConfigResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE UpdateConfigResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void UpdateConfigResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, http_compression_),
           0,
           offsetof(Impl_, https_) -
               offsetof(Impl_, http_compression_) +
               sizeof(Impl_::https_));
}
UpdateConfigResponse::~UpdateConfigResponse() {
  // @@protoc_insertion_point(destructor:api.v1.UpdateConfigResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UpdateConfigResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    UpdateConfigResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_UpdateConfigResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &UpdateConfigResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<UpdateConfigResponse>(),
            ::google::protobuf::Message::GetNewImpl<UpdateConfigResponse>(),
            ::google::protobuf::Message::GetClearImpl<UpdateConfigResponse>(), &UpdateConfigResponse::ByteSizeLong,
                &UpdateConfigResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(UpdateConfigResponse, _impl_._cached_size_),
            false,
        },
        &UpdateConfigResponse::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* UpdateConfigResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> UpdateConfigResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::UpdateConfigResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool https = 2 [json_name = "https"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UpdateConfigResponse, _impl_.https_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateConfigResponse, _impl_.https_)}},
    // bool http_compression = 1 [json_name = "httpCompression"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UpdateConfigResponse, _impl_.http_compression_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateConfigResponse, _impl_.http_compression_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool http_compression = 1 [json_name = "httpCompression"];
    {PROTOBUF_FIELD_OFFSET(UpdateConfigResponse, _impl_.http_compression_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool https = 2 [json_name = "https"];
    {PROTOBUF_FIELD_OFFSET(UpdateConfigResponse, _impl_.https_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void UpdateConfigResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:api.v1.UpdateConfigResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.http_compression_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.https_) -
      reinterpret_cast<char*>(&_impl_.http_compression_)) + sizeof(_impl_.https_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateConfigResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateConfigResponse& this_ = static_cast<const UpdateConfigResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateConfigResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateConfigResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.v1.UpdateConfigResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool http_compression = 1 [json_name = "httpCompression"];
          if (this_._internal_http_compression() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_http_compression(), target);
          }

          // bool https = 2 [json_name = "https"];
          if (this_._internal_https() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_https(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.v1.UpdateConfigResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateConfigResponse::ByteSizeLong(const MessageLite& base) {
          const UpdateConfigResponse& this_ = static_cast<const UpdateConfigResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateConfigResponse::ByteSizeLong() const {
          const UpdateConfigResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.v1.UpdateConfigResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bool http_compression = 1 [json_name = "httpCompression"];
            if (this_._internal_http_compression() != 0) {
              total_size += 2;
            }
            // bool https = 2 [json_name = "https"];
            if (this_._internal_https() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateConfigResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateConfigResponse*>(&to_msg);
  auto& from = static_cast<const UpdateConfigResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.v1.UpdateConfigResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_http_compression() != 0) {
    _this->_impl_.http_compression_ = from._impl_.http_compression_;
  }
  if (from._internal_https() != 0) {
    _this->_impl_.https_ = from._impl_.https_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateConfigResponse::CopyFrom(const UpdateConfigResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.v1.UpdateConfigResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateConfigResponse::InternalSwap(UpdateConfigResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateConfigResponse, _impl_.https_)
      + sizeof(UpdateConfigResponse::_impl_.https_)
      - PROTOBUF_FIELD_OFFSET(UpdateConfigResponse, _impl_.http_compression_)>(
          reinterpret_cast<char*>(&_impl_.http_compression_),
          reinterpret_cast<char*>(&other->_impl_.http_compression_));
}

::google::protobuf::Metadata UpdateConfigResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetIpBlackListRequest::_Internal {
 public:
};

GetIpBlackListRequest::GetIpBlackListRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:api.v1.GetIpBlackListRequest)
}
GetIpBlackListRequest::GetIpBlackListRequest(
    ::google::protobuf::Arena* arena,
    const GetIpBlackListRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetIpBlackListRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:api.v1.GetIpBlackListRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetIpBlackListRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_GetIpBlackListRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetIpBlackListRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<GetIpBlackListRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<GetIpBlackListRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<GetIpBlackListRequest>(), &GetIpBlackListRequest::ByteSizeLong,
                &GetIpBlackListRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetIpBlackListRequest, _impl_._cached_size_),
            false,
        },
        &GetIpBlackListRequest::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetIpBlackListRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> GetIpBlackListRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::GetIpBlackListRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata GetIpBlackListRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetIpBlackListResponse::_Internal {
 public:
};

GetIpBlackListResponse::GetIpBlackListResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.v1.GetIpBlackListResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetIpBlackListResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::api::v1::GetIpBlackListResponse& from_msg)
      : ip_list_{visibility, arena, from.ip_list_},
        _cached_size_{0} {}

GetIpBlackListResponse::GetIpBlackListResponse(
    ::google::protobuf::Arena* arena,
    const GetIpBlackListResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetIpBlackListResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:api.v1.GetIpBlackListResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetIpBlackListResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : ip_list_{visibility, arena},
        _cached_size_{0} {}

inline void GetIpBlackListResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetIpBlackListResponse::~GetIpBlackListResponse() {
  // @@protoc_insertion_point(destructor:api.v1.GetIpBlackListResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetIpBlackListResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetIpBlackListResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetIpBlackListResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetIpBlackListResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetIpBlackListResponse>(),
            ::google::protobuf::Message::GetNewImpl<GetIpBlackListResponse>(),
            ::google::protobuf::Message::GetClearImpl<GetIpBlackListResponse>(), &GetIpBlackListResponse::ByteSizeLong,
                &GetIpBlackListResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetIpBlackListResponse, _impl_._cached_size_),
            false,
        },
        &GetIpBlackListResponse::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetIpBlackListResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 45, 2> GetIpBlackListResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::GetIpBlackListResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string ip_list = 1 [json_name = "ipList"];
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetIpBlackListResponse, _impl_.ip_list_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string ip_list = 1 [json_name = "ipList"];
    {PROTOBUF_FIELD_OFFSET(GetIpBlackListResponse, _impl_.ip_list_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\35\7\0\0\0\0\0\0"
    "api.v1.GetIpBlackListResponse"
    "ip_list"
  }},
};

PROTOBUF_NOINLINE void GetIpBlackListResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:api.v1.GetIpBlackListResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_list_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetIpBlackListResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetIpBlackListResponse& this_ = static_cast<const GetIpBlackListResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetIpBlackListResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetIpBlackListResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.v1.GetIpBlackListResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string ip_list = 1 [json_name = "ipList"];
          for (int i = 0, n = this_._internal_ip_list_size(); i < n; ++i) {
            const auto& s = this_._internal_ip_list().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "api.v1.GetIpBlackListResponse.ip_list");
            target = stream->WriteString(1, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.v1.GetIpBlackListResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetIpBlackListResponse::ByteSizeLong(const MessageLite& base) {
          const GetIpBlackListResponse& this_ = static_cast<const GetIpBlackListResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetIpBlackListResponse::ByteSizeLong() const {
          const GetIpBlackListResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.v1.GetIpBlackListResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string ip_list = 1 [json_name = "ipList"];
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_ip_list().size());
              for (int i = 0, n = this_._internal_ip_list().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_ip_list().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetIpBlackListResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetIpBlackListResponse*>(&to_msg);
  auto& from = static_cast<const GetIpBlackListResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.v1.GetIpBlackListResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_ip_list()->MergeFrom(from._internal_ip_list());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetIpBlackListResponse::CopyFrom(const GetIpBlackListResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.v1.GetIpBlackListResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetIpBlackListResponse::InternalSwap(GetIpBlackListResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ip_list_.InternalSwap(&other->_impl_.ip_list_);
}

::google::protobuf::Metadata GetIpBlackListResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateIpBlackListRequest::_Internal {
 public:
};

UpdateIpBlackListRequest::UpdateIpBlackListRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.v1.UpdateIpBlackListRequest)
}
inline PROTOBUF_NDEBUG_INLINE UpdateIpBlackListRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::api::v1::UpdateIpBlackListRequest& from_msg)
      : ip_list_{visibility, arena, from.ip_list_},
        _cached_size_{0} {}

UpdateIpBlackListRequest::UpdateIpBlackListRequest(
    ::google::protobuf::Arena* arena,
    const UpdateIpBlackListRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateIpBlackListRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.action_ = from._impl_.action_;

  // @@protoc_insertion_point(copy_constructor:api.v1.UpdateIpBlackListRequest)
}
inline PROTOBUF_NDEBUG_INLINE UpdateIpBlackListRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : ip_list_{visibility, arena},
        _cached_size_{0} {}

inline void UpdateIpBlackListRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.action_ = {};
}
UpdateIpBlackListRequest::~UpdateIpBlackListRequest() {
  // @@protoc_insertion_point(destructor:api.v1.UpdateIpBlackListRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UpdateIpBlackListRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    UpdateIpBlackListRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_UpdateIpBlackListRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &UpdateIpBlackListRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<UpdateIpBlackListRequest>(),
            ::google::protobuf::Message::GetNewImpl<UpdateIpBlackListRequest>(),
            ::google::protobuf::Message::GetClearImpl<UpdateIpBlackListRequest>(), &UpdateIpBlackListRequest::ByteSizeLong,
                &UpdateIpBlackListRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(UpdateIpBlackListRequest, _impl_._cached_size_),
            false,
        },
        &UpdateIpBlackListRequest::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* UpdateIpBlackListRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 47, 2> UpdateIpBlackListRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::UpdateIpBlackListRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string ip_list = 2 [json_name = "ipList"];
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateIpBlackListRequest, _impl_.ip_list_)}},
    // .api.v1.UpdateIpBlackListRequest.ActionType action = 1 [json_name = "action"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateIpBlackListRequest, _impl_.action_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateIpBlackListRequest, _impl_.action_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .api.v1.UpdateIpBlackListRequest.ActionType action = 1 [json_name = "action"];
    {PROTOBUF_FIELD_OFFSET(UpdateIpBlackListRequest, _impl_.action_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated string ip_list = 2 [json_name = "ipList"];
    {PROTOBUF_FIELD_OFFSET(UpdateIpBlackListRequest, _impl_.ip_list_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\37\0\7\0\0\0\0\0"
    "api.v1.UpdateIpBlackListRequest"
    "ip_list"
  }},
};

PROTOBUF_NOINLINE void UpdateIpBlackListRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:api.v1.UpdateIpBlackListRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_list_.Clear();
  _impl_.action_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateIpBlackListRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateIpBlackListRequest& this_ = static_cast<const UpdateIpBlackListRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateIpBlackListRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateIpBlackListRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.v1.UpdateIpBlackListRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .api.v1.UpdateIpBlackListRequest.ActionType action = 1 [json_name = "action"];
          if (this_._internal_action() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_action(), target);
          }

          // repeated string ip_list = 2 [json_name = "ipList"];
          for (int i = 0, n = this_._internal_ip_list_size(); i < n; ++i) {
            const auto& s = this_._internal_ip_list().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "api.v1.UpdateIpBlackListRequest.ip_list");
            target = stream->WriteString(2, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.v1.UpdateIpBlackListRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateIpBlackListRequest::ByteSizeLong(const MessageLite& base) {
          const UpdateIpBlackListRequest& this_ = static_cast<const UpdateIpBlackListRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateIpBlackListRequest::ByteSizeLong() const {
          const UpdateIpBlackListRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.v1.UpdateIpBlackListRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string ip_list = 2 [json_name = "ipList"];
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_ip_list().size());
              for (int i = 0, n = this_._internal_ip_list().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_ip_list().Get(i));
              }
            }
          }
           {
            // .api.v1.UpdateIpBlackListRequest.ActionType action = 1 [json_name = "action"];
            if (this_._internal_action() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_action());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateIpBlackListRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateIpBlackListRequest*>(&to_msg);
  auto& from = static_cast<const UpdateIpBlackListRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.v1.UpdateIpBlackListRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_ip_list()->MergeFrom(from._internal_ip_list());
  if (from._internal_action() != 0) {
    _this->_impl_.action_ = from._impl_.action_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateIpBlackListRequest::CopyFrom(const UpdateIpBlackListRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.v1.UpdateIpBlackListRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateIpBlackListRequest::InternalSwap(UpdateIpBlackListRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ip_list_.InternalSwap(&other->_impl_.ip_list_);
  swap(_impl_.action_, other->_impl_.action_);
}

::google::protobuf::Metadata UpdateIpBlackListRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateIpBlackListResponse::_Internal {
 public:
};

UpdateIpBlackListResponse::UpdateIpBlackListResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:api.v1.UpdateIpBlackListResponse)
}
UpdateIpBlackListResponse::UpdateIpBlackListResponse(
    ::google::protobuf::Arena* arena,
    const UpdateIpBlackListResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateIpBlackListResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:api.v1.UpdateIpBlackListResponse)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    UpdateIpBlackListResponse::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_UpdateIpBlackListResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &UpdateIpBlackListResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<UpdateIpBlackListResponse>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<UpdateIpBlackListResponse>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<UpdateIpBlackListResponse>(), &UpdateIpBlackListResponse::ByteSizeLong,
                &UpdateIpBlackListResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(UpdateIpBlackListResponse, _impl_._cached_size_),
            false,
        },
        &UpdateIpBlackListResponse::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* UpdateIpBlackListResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> UpdateIpBlackListResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::UpdateIpBlackListResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata UpdateIpBlackListResponse::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_config_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
