// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: config_service.proto
// Protobuf C++ Version: 5.28.3

#include "config_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace api {
namespace v1 {

inline constexpr GetConfigResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : config_value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetConfigResponse::GetConfigResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetConfigResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetConfigResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetConfigResponseDefaultTypeInternal() {}
  union {
    GetConfigResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetConfigResponseDefaultTypeInternal _GetConfigResponse_default_instance_;

inline constexpr GetConfigRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : config_key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetConfigRequest::GetConfigRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetConfigRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetConfigRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetConfigRequestDefaultTypeInternal() {}
  union {
    GetConfigRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetConfigRequestDefaultTypeInternal _GetConfigRequest_default_instance_;
}  // namespace v1
}  // namespace api
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_config_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_config_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_config_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::GetConfigRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::v1::GetConfigRequest, _impl_.config_key_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::v1::GetConfigResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::v1::GetConfigResponse, _impl_.config_value_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::api::v1::GetConfigRequest)},
        {9, -1, -1, sizeof(::api::v1::GetConfigResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::api::v1::_GetConfigRequest_default_instance_._instance,
    &::api::v1::_GetConfigResponse_default_instance_._instance,
};
const char descriptor_table_protodef_config_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024config_service.proto\022\006api.v1\"1\n\020GetCon"
    "figRequest\022\035\n\nconfig_key\030\001 \001(\tR\tconfigKe"
    "y\"6\n\021GetConfigResponse\022!\n\014config_value\030\001"
    " \001(\tR\013configValue2Q\n\rConfigService\022@\n\tGe"
    "tConfig\022\030.api.v1.GetConfigRequest\032\031.api."
    "v1.GetConfigResponseBY\n\ncom.api.v1B\022Conf"
    "igServiceProtoP\001\242\002\003AXX\252\002\006Api.V1\312\002\006Api\\V1"
    "\342\002\022Api\\V1\\GPBMetadata\352\002\007Api::V1b\006proto3"
};
static ::absl::once_flag descriptor_table_config_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_config_5fservice_2eproto = {
    false,
    false,
    319,
    descriptor_table_protodef_config_5fservice_2eproto,
    "config_service.proto",
    &descriptor_table_config_5fservice_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_config_5fservice_2eproto::offsets,
    file_level_enum_descriptors_config_5fservice_2eproto,
    file_level_service_descriptors_config_5fservice_2eproto,
};
namespace api {
namespace v1 {
// ===================================================================

class GetConfigRequest::_Internal {
 public:
};

GetConfigRequest::GetConfigRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.v1.GetConfigRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetConfigRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::api::v1::GetConfigRequest& from_msg)
      : config_key_(arena, from.config_key_),
        _cached_size_{0} {}

GetConfigRequest::GetConfigRequest(
    ::google::protobuf::Arena* arena,
    const GetConfigRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetConfigRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:api.v1.GetConfigRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetConfigRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : config_key_(arena),
        _cached_size_{0} {}

inline void GetConfigRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetConfigRequest::~GetConfigRequest() {
  // @@protoc_insertion_point(destructor:api.v1.GetConfigRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetConfigRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.config_key_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetConfigRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetConfigRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetConfigRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetConfigRequest>(),
            ::google::protobuf::Message::GetNewImpl<GetConfigRequest>(),
            ::google::protobuf::Message::GetClearImpl<GetConfigRequest>(), &GetConfigRequest::ByteSizeLong,
                &GetConfigRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetConfigRequest, _impl_._cached_size_),
            false,
        },
        &GetConfigRequest::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetConfigRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 42, 2> GetConfigRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::GetConfigRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string config_key = 1 [json_name = "configKey"];
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetConfigRequest, _impl_.config_key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string config_key = 1 [json_name = "configKey"];
    {PROTOBUF_FIELD_OFFSET(GetConfigRequest, _impl_.config_key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\12\0\0\0\0\0\0"
    "api.v1.GetConfigRequest"
    "config_key"
  }},
};

PROTOBUF_NOINLINE void GetConfigRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:api.v1.GetConfigRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.config_key_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetConfigRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetConfigRequest& this_ = static_cast<const GetConfigRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetConfigRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetConfigRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.v1.GetConfigRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string config_key = 1 [json_name = "configKey"];
          if (!this_._internal_config_key().empty()) {
            const std::string& _s = this_._internal_config_key();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "api.v1.GetConfigRequest.config_key");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.v1.GetConfigRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetConfigRequest::ByteSizeLong(const MessageLite& base) {
          const GetConfigRequest& this_ = static_cast<const GetConfigRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetConfigRequest::ByteSizeLong() const {
          const GetConfigRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.v1.GetConfigRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string config_key = 1 [json_name = "configKey"];
            if (!this_._internal_config_key().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_config_key());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetConfigRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetConfigRequest*>(&to_msg);
  auto& from = static_cast<const GetConfigRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.v1.GetConfigRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_config_key().empty()) {
    _this->_internal_set_config_key(from._internal_config_key());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetConfigRequest::CopyFrom(const GetConfigRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.v1.GetConfigRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetConfigRequest::InternalSwap(GetConfigRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.config_key_, &other->_impl_.config_key_, arena);
}

::google::protobuf::Metadata GetConfigRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetConfigResponse::_Internal {
 public:
};

GetConfigResponse::GetConfigResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.v1.GetConfigResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetConfigResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::api::v1::GetConfigResponse& from_msg)
      : config_value_(arena, from.config_value_),
        _cached_size_{0} {}

GetConfigResponse::GetConfigResponse(
    ::google::protobuf::Arena* arena,
    const GetConfigResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetConfigResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:api.v1.GetConfigResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetConfigResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : config_value_(arena),
        _cached_size_{0} {}

inline void GetConfigResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetConfigResponse::~GetConfigResponse() {
  // @@protoc_insertion_point(destructor:api.v1.GetConfigResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetConfigResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.config_value_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetConfigResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetConfigResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetConfigResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetConfigResponse>(),
            ::google::protobuf::Message::GetNewImpl<GetConfigResponse>(),
            ::google::protobuf::Message::GetClearImpl<GetConfigResponse>(), &GetConfigResponse::ByteSizeLong,
                &GetConfigResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetConfigResponse, _impl_._cached_size_),
            false,
        },
        &GetConfigResponse::kDescriptorMethods,
        &descriptor_table_config_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetConfigResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 45, 2> GetConfigResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::v1::GetConfigResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string config_value = 1 [json_name = "configValue"];
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetConfigResponse, _impl_.config_value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string config_value = 1 [json_name = "configValue"];
    {PROTOBUF_FIELD_OFFSET(GetConfigResponse, _impl_.config_value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\14\0\0\0\0\0\0"
    "api.v1.GetConfigResponse"
    "config_value"
  }},
};

PROTOBUF_NOINLINE void GetConfigResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:api.v1.GetConfigResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.config_value_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetConfigResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetConfigResponse& this_ = static_cast<const GetConfigResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetConfigResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetConfigResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.v1.GetConfigResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string config_value = 1 [json_name = "configValue"];
          if (!this_._internal_config_value().empty()) {
            const std::string& _s = this_._internal_config_value();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "api.v1.GetConfigResponse.config_value");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.v1.GetConfigResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetConfigResponse::ByteSizeLong(const MessageLite& base) {
          const GetConfigResponse& this_ = static_cast<const GetConfigResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetConfigResponse::ByteSizeLong() const {
          const GetConfigResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.v1.GetConfigResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string config_value = 1 [json_name = "configValue"];
            if (!this_._internal_config_value().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_config_value());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetConfigResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetConfigResponse*>(&to_msg);
  auto& from = static_cast<const GetConfigResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.v1.GetConfigResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_config_value().empty()) {
    _this->_internal_set_config_value(from._internal_config_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetConfigResponse::CopyFrom(const GetConfigResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.v1.GetConfigResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetConfigResponse::InternalSwap(GetConfigResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.config_value_, &other->_impl_.config_value_, arena);
}

::google::protobuf::Metadata GetConfigResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_config_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
